project:
  type: website

website:
  navbar:
    left:
      - href: about.qmd
        text: Home
      - href: projects.qmd
        text: Projects

  page-footer:
    right: "&copy; 2024, Jason Scruggs"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
  
